import Head from "next/head";
import { connect } from "getstream";

export default function Home({ token }: { token: string }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const client = connect(
    "x2u4y9padhyg",
    "a3jgbre8tjq5j3q3twzw72rce3xgm72p2szuq422j3kffzbe4yh7ksspsqz4kwh3"
  );

  const token = await client.createUserToken("emanatelive");

  return {
    props: {
      token,
    },
  };
}
